name: Build Hexagonal

on:
  pull_request:
    branches:
      - main
    paths:
      - hexagonal/**
  push:
    branches:
      - main
    paths:
      - hexagonal/**

jobs:
  
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: 21
        distribution: temurin
    - uses: gradle/actions/setup-gradle@v3
    - run: ./gradlew build
